### ISSUE TITLE
Crash when start android

### ISSUE THREAD

**Issue by whalemare** [kristerkari/react-native-svg-example#2]
Doing all step-by-step for run demo project.

Also add `local.properties` file manually to `android` folder work build success. 

when start `npm run android` app installed and crashes with stacktrace:

```
I/ActivityManager( 1488): Displayed com.svgdemo/.MainActivity: +510ms
E/AndroidRuntime(12396): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime(12396): Process: com.svgdemo, PID: 12396
E/AndroidRuntime(12396): java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING
E/AndroidRuntime(12396):        at android.util.JsonReader.expect(JsonReader.java:310)
E/AndroidRuntime(12396):        at android.util.JsonReader.beginArray(JsonReader.java:277)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.patchDelta(BundleDeltaClient.java:150)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:104)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDeltaClient.processDelta(BundleDeltaClient.java:71)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:314)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:37)
E/AndroidRuntime(12396):        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:174)
E/AndroidRuntime(12396):        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
E/AndroidRuntime(12396):        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime(12396):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(12396):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(12396):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1488):   Force finishing activity 1 com.svgdemo/.MainActivity
```

**Comment by kristerkari** [comment]
Thanks @whalemare! I updated the project to React Native v0.58.6. Can you try again to see if it works now?

**Comment by kristerkari** [comment]
Closing this because of inactivity. Let's re-open if something new comes up.
